# Default values for my-laravel-chart.
image:
  repository: my-laravel-app
  pullPolicy: IfNotPresent
  tag: ""

# Внешние зависимости
externalDatabase:
  host: "your-postgres-cluster.yandex.cloud"  # Подставьте реальный хост
  port: 5432
  database: laravel
  username: laravel
  password: ""  # Будет передан через Secret

externalRedis:
  host: "your-redis-cluster.yandex.cloud"     # Подставьте реальный хост
  port: 6379
  password: ""
  db: 0
  cacheDb: 1

# Laravel env vars
laravel:
  appEnv: production
  appDebug: false
  appKey: "base64:pX5dF0MJvDJBBgX90kHHhoc3+I7v7zYL428PO4PHZJ4="
  moonshineUsername: admin@example.com
  moonshineName: Admin
  moonshinePassword: 111111

# Deployment
replicaCount: 2
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: myapp.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: myapp-tls
      hosts:
        - myapp.example.com

# Queue workers
queueWorkers:
  replicaCount: 2
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Scheduler worker
schedulerWorker:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Storage
persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
